### ISSUE TITLE
Пожелание про деревья.

### ISSUE THREAD

**Issue by Zebrix** [SpeeeDCraft/Ideal-Industrial-Modpack-1.12.2#4]
Зачем в сборке про автоматизацию Dynamic trees? Я бы не стал добавлять этого пожирателя FPS. а уж какой толк в технической сборке, где а автоферму обычные деревья заталкивать?

**Comment by SpeeeDCraft** [comment]
Подумаем.

**Comment by SpeeeDCraft** [comment]
DynamicTrees очень хорошо разбавляет дефолтный ландшафт майнкрафта. Как ни крути я соглашусь, что фпс он жрет, но не сильно, так как хорошо оптимизирован(версия аддон для TFC вообще не оптимизирована по-моему). Но есть один факт. Что можно делать обычные саженцы через ведро с землей. И если ты или кто-то другой хочет использовать фермы(а у нас на сервере уже используют такую систему), то саженцы можно перекрафтить в дефолтные и их давать ферме, чтобы та выращивала и собирала. С этим проблем никаких нет. Поэтому я считаю удаление DynamicTrees не целесообразным. :/
