### ISSUE TITLE
[Suggestion] add Super Tank and Super Chest using DevTech

### ISSUE THREAD

**Issue by bioastroiner** [SpeeeDCraft/Ideal-Industrial-Modpack-1.12.2#7]
I don't know if you have played Gregicality's Community Pack, It basically uses a Gregicality Addon to Add custom (Greggy?) blocks and tileEntities to gregtech, so they made Super Tanks and Super Chest witch are way smaller versions of Quantum Tanks (witch require osmium witch comes in at least IV age!! ohboi) since other mods' Tanks are disbaled in this pack and Gregtech CE Tanks are really shit, Super Tanks are very good addition and keep the asthetic of Gregtech especially that it also was in GTNH (i think bartwork? or gt++)
not sure how exactly it works, but the addition of this .zs files would get the job done (except for the stock Manipulator Section)
whatever rolls your gears
link to the mod: https://www.curseforge.com/minecraft/mc-mods/devtech
GTCP's ZenScript files: https://github.com/Gregicality/Gregicality-Community-Pack/tree/master/scripts/devtech
Also the wiki: https://github.com/idcppl/DevTech/wiki/Register-Machines

wish the super tanks were part of gregicality but heh probably soon

**Comment by SpeeeDCraft** [comment]
It looks good. The tanks of the usual GregTechCE really look bad. I will add this one in the 1.6 update.

**Comment by SpeeeDCraft** [comment]
Added in last commit
